#! /bin/bash
HOST="ratnavali"
SHARED_KEY=123
ENDPOINT="http://192.168.144.10/dynDnsEP/"
TS=$(date +%s)
VS=$HOST$TS$SHARED_KEY
#echo $VS
OP="$(echo -ne $VS| sha256sum | head -c64)";
PS="HOST=$HOST&SIG=$OP&TS=$TS"
#echo "==============="
curl --data $PS $ENDPOINT